import React, { useEffect, useState } from 'react';
import { Card, CardBody } from 'shards-react';
import { WelcomeCardContainer } from './styles';
import { LeonSans } from '../../leon';

const WelcomeCard = () => {
  const [fontWeight, setFontWeight] = useState(200);
  let leon, canvas, ctx;

  const sw = 800;
  const sh = 600;
  const pixelRatio = 10;

  function init() {
    canvas = document.querySelector('.textCanvas');

    ctx = canvas.getContext('2d');

    canvas.width = sw * pixelRatio;
    canvas.height = sh * pixelRatio;
    canvas.style.width = sw + 'px';
    canvas.style.height = sh + 'px';
    ctx.scale(pixelRatio, pixelRatio);

    leon = new LeonSans({
      text: 'The quick brown\nfox jumps over\nthe lazy dog',
      color: ['#000000'],
      size: 80,
      weight: fontWeight
    });

    requestAnimationFrame(animate);
  }
  const animateWeight = () => {
    for (let i = 100; i < 901; i + 100) {
      setFontWeight(i);
    }
  };

  function animate(t) {
    requestAnimationFrame(animate);

    ctx.clearRect(0, 0, sw, sh);

    const x = (sw - leon.rect.w) / 2;
    const y = (sh - leon.rect.h) / 2;
    leon.position(x, y);

    leon.draw(ctx);
  }
  useEffect(init, []);
  useEffect(animateWeight, []);

  return (
    <div>
      <WelcomeCardContainer>
        <Card>
          <CardBody>
            <h3>Welcome to Iambic.dev</h3>
            <canvas className='textCanvas' />
            <p>
              All the poems on this site are generated by an AI. Register or
              Login to be able to post, the above poem and vote on plenty
              others!{' '}
            </p>
          </CardBody>
        </Card>
      </WelcomeCardContainer>
    </div>
  );
};

export default WelcomeCard;
